/* Sample PDF generators for Corner Streams landing-page showcase. */
import jsPDF from "jspdf";

const NAVY = "#002147";
const GREEN = "#28A745";
const BLUE = "#0056B3";

function header(doc, title, sub) {
  doc.setFillColor(NAVY);
  doc.rect(0, 0, 210, 28, "F");
  doc.setTextColor("#FFFFFF");
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("CORNER STREAMS", 14, 13);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("Taking away the paper trap.", 14, 20);
  doc.setFontSize(8);
  doc.setTextColor("#A7C0DA");
  doc.text("SAMPLE — Not an official document", 145, 13);

  doc.setTextColor(NAVY);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(title, 14, 42);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor("#475569");
  doc.text(sub, 14, 49);

  doc.setDrawColor(GREEN);
  doc.setLineWidth(0.8);
  doc.line(14, 53, 196, 53);
}

function footer(doc) {
  doc.setFontSize(8);
  doc.setTextColor("#94A3B8");
  doc.text("Generated by Corner Streams · cornerstreams.ng · QR-verified document sample", 14, 285);
}

export function generateSampleReportCard() {
  const doc = new jsPDF();
  header(doc, "Student Term Report", "Adaeze Okonkwo · JSS 2 · 2nd Term · 2025/2026");

  // Student summary
  doc.setFontSize(10);
  doc.setTextColor(NAVY);
  doc.setFont("helvetica", "bold");
  doc.text("Student ID:", 14, 64);    doc.setFont("helvetica", "normal"); doc.text("CS-LAG-0042", 40, 64);
  doc.setFont("helvetica", "bold");   doc.text("Class:", 80, 64);          doc.setFont("helvetica", "normal"); doc.text("JSS 2 — Bronze", 95, 64);
  doc.setFont("helvetica", "bold");   doc.text("Position:", 140, 64);      doc.setFont("helvetica", "normal"); doc.text("3 of 28", 162, 64);
  doc.setFont("helvetica", "bold");   doc.text("Attendance:", 14, 71);     doc.setFont("helvetica", "normal"); doc.text("58 / 60 days", 45, 71);

  // Scores table
  const rows = [
    ["Mathematics", 28, 62, 90, "A", "Excellent grasp of algebra."],
    ["English Language", 25, 55, 80, "B", "Strong essays; revise tenses."],
    ["Basic Science", 27, 58, 85, "A", "Outstanding lab participation."],
    ["Civic Education", 22, 50, 72, "C", "Good. Engage more in class."],
    ["Computer Studies", 29, 64, 93, "A", "Top of class. Excellent CBT."],
    ["Yoruba", 20, 48, 68, "C", "Improve vocabulary."],
    ["Agricultural Sci.", 26, 57, 83, "B", "Sound effort overall."],
  ];

  let y = 82;
  doc.setFillColor(NAVY);
  doc.rect(14, y - 6, 182, 8, "F");
  doc.setTextColor("#FFFFFF");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  ["Subject", "CA (30)", "Exam (70)", "Total", "Grade", "Teacher's Remark"].forEach((h, i) => {
    const x = [16, 70, 92, 116, 138, 158][i];
    doc.text(h, x, y - 1);
  });

  doc.setFont("helvetica", "normal");
  doc.setTextColor(NAVY);
  rows.forEach((r, i) => {
    y += 9;
    if (i % 2 === 0) {
      doc.setFillColor("#F1F5F9");
      doc.rect(14, y - 6, 182, 8, "F");
    }
    doc.setFontSize(9);
    doc.text(String(r[0]), 16, y);
    doc.text(String(r[1]), 76, y);
    doc.text(String(r[2]), 100, y);
    doc.setFont("helvetica", "bold");
    doc.text(String(r[3]), 120, y);
    doc.setFont("helvetica", "normal");
    doc.text(String(r[4]), 144, y);
    doc.setFontSize(8);
    doc.text(String(r[5]).slice(0, 26), 158, y);
    doc.setFontSize(9);
  });

  // Summary stats
  y += 16;
  doc.setFillColor("#ECFDF5");
  doc.rect(14, y, 88, 30, "F");
  doc.setTextColor(GREEN);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("AVERAGE", 18, y + 8);
  doc.setFontSize(22);
  doc.text("81.6 %", 18, y + 22);

  doc.setFillColor("#EFF6FF");
  doc.rect(108, y, 88, 30, "F");
  doc.setTextColor(BLUE);
  doc.setFontSize(10);
  doc.text("GRADE", 112, y + 8);
  doc.setFontSize(22);
  doc.text("A · Distinction", 112, y + 22);

  // Skills
  y += 40;
  doc.setTextColor(NAVY);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Affective & Psychomotor Skills", 14, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  const skills = [
    ["Punctuality", 5],
    ["Neatness", 4],
    ["Leadership", 5],
    ["Sports", 3],
    ["Honesty", 5],
    ["Class Participation", 4],
  ];
  skills.forEach((s, i) => {
    const sy = y + 8 + i * 6;
    doc.text(s[0], 14, sy);
    doc.setTextColor(GREEN);
    doc.text("★".repeat(s[1]) + "☆".repeat(5 - s[1]), 70, sy);
    doc.setTextColor(NAVY);
  });

  // Principal's note
  y += 56;
  doc.setFillColor("#F8FAFC");
  doc.rect(14, y, 182, 24, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("Principal's Remark", 18, y + 7);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("Adaeze is a focused and conscientious student. Her CBT discipline is exemplary.", 18, y + 14);
  doc.text("She is encouraged to mentor classmates. — Mrs. Adaeze Okonkwo, Principal", 18, y + 20);

  // QR placeholder
  doc.setDrawColor(NAVY);
  doc.rect(170, y - 36, 22, 22);
  doc.setFontSize(6);
  doc.setTextColor("#475569");
  doc.text("QR-verified", 173, y - 12);

  footer(doc);
  doc.save("CornerStreams_SampleReportCard.pdf");
}

export function generateSampleCBT() {
  const doc = new jsPDF();
  header(doc, "CBT Examination Script", "Mathematics · JSS 2 · 2nd Term · Duration: 45 min");

  doc.setFontSize(10);
  doc.setTextColor(NAVY);
  doc.setFont("helvetica", "bold");
  doc.text("Candidate:", 14, 64);  doc.setFont("helvetica", "normal"); doc.text("Adaeze Okonkwo (CS-LAG-0042)", 35, 64);
  doc.setFont("helvetica", "bold"); doc.text("Score:", 120, 64); doc.setFont("helvetica", "normal"); doc.text("18 / 20  (90%)", 135, 64);
  doc.setFont("helvetica", "bold"); doc.text("Submitted:", 14, 71); doc.setFont("helvetica", "normal"); doc.text("12 Feb 2026 · 10:47 AM WAT · IP 41.59.21.* ", 35, 71);

  const questions = [
    ["1.", "Solve: 3x + 5 = 20", ["x = 4", "x = 5", "x = 6", "x = 7"], 1, 1],
    ["2.", "What is the value of π to 2 dp?", ["3.12", "3.14", "3.16", "3.18"], 1, 1],
    ["3.", "If a triangle has angles 60°, 60°, 60° it is…", ["Right-angled", "Isosceles", "Equilateral", "Scalene"], 2, 2],
    ["4.", "Simplify: 2(x + 3) - x", ["x + 6", "x + 3", "x + 9", "3x + 3"], 0, 0],
    ["5.", "Convert 0.25 to a fraction", ["1/2", "1/3", "1/4", "1/5"], 2, 2],
    ["6.", "What is the area of a square of side 7 cm?", ["14 cm²", "28 cm²", "49 cm²", "56 cm²"], 2, 2],
    ["7.", "Solve: 12 ÷ 3 × 2", ["2", "4", "8", "12"], 2, 1],
  ];

  let y = 84;
  doc.setFontSize(9);
  questions.forEach((q) => {
    doc.setFont("helvetica", "bold");
    doc.setTextColor(NAVY);
    doc.text(`${q[0]} ${q[1]}`, 14, y);
    y += 6;
    q[2].forEach((opt, idx) => {
      const isCorrect = idx === q[4];
      const isPicked = idx === q[3];
      doc.setFont("helvetica", "normal");
      if (isCorrect && isPicked) doc.setTextColor(GREEN);
      else if (isPicked && !isCorrect) doc.setTextColor("#DC2626");
      else if (isCorrect) doc.setTextColor(GREEN);
      else doc.setTextColor("#475569");
      const marker = isPicked ? "●" : "○";
      doc.text(`${marker} ${String.fromCharCode(65 + idx)}. ${opt}`, 20, y);
      if (isPicked && !isCorrect) doc.text("← student answer", 110, y);
      if (isCorrect) doc.text("← correct", 150, y);
      y += 5;
    });
    y += 4;
  });

  // Summary box
  doc.setFillColor("#ECFDF5");
  doc.rect(14, 250, 88, 26, "F");
  doc.setTextColor(GREEN);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("AUTO-GRADED", 18, 258);
  doc.setFontSize(20);
  doc.text("90 %", 18, 272);

  doc.setFillColor("#EFF6FF");
  doc.rect(108, 250, 88, 26, "F");
  doc.setTextColor(BLUE);
  doc.setFontSize(10);
  doc.text("STATUS", 112, 258);
  doc.setFontSize(14);
  doc.text("Synced to Term Ledger ✓", 112, 270);

  footer(doc);
  doc.save("CornerStreams_SampleCBT.pdf");
}

export function generateSampleFinance() {
  const doc = new jsPDF();
  header(doc, "School Financial Statement", "Sunrise Academy · February 2026 · Reconciled");

  doc.setFontSize(10);
  doc.setTextColor(NAVY);
  doc.setFont("helvetica", "bold");
  doc.text("Period:", 14, 64);   doc.setFont("helvetica", "normal"); doc.text("01–28 Feb 2026", 32, 64);
  doc.setFont("helvetica", "bold"); doc.text("Prepared by:", 90, 64); doc.setFont("helvetica", "normal"); doc.text("Mr. Tunde Bakare (Bursar)", 118, 64);
  doc.setFont("helvetica", "bold"); doc.text("Approved by:", 14, 71); doc.setFont("helvetica", "normal"); doc.text("Mrs. Adaeze Okonkwo (Principal)", 42, 71);

  // Header bar
  let y = 84;
  doc.setFillColor(NAVY);
  doc.rect(14, y - 6, 182, 8, "F");
  doc.setTextColor("#FFFFFF");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  ["#", "Description", "Channel", "Reference", "Debit (₦)", "Credit (₦)"].forEach((h, i) => {
    const x = [16, 26, 80, 110, 145, 175][i];
    doc.text(h, x, y - 1);
  });

  const rows = [
    ["01", "Term-fee — JSS 2 — Adaeze Okonkwo", "Card", "stripe_ch_1Nz...", "—", "120,000"],
    ["02", "Term-fee — JSS 1 — Chinedu Eze",   "Card", "stripe_ch_2Aa...", "—",  "95,000"],
    ["03", "Term-fee — SS 1 — Habibah Bello",  "Bank", "FBN-TRF-441",     "—", "150,000"],
    ["04", "PTA dues — class JSS 2",           "Bank", "FBN-TRF-450",     "—",  "28,000"],
    ["05", "Salaries — teaching staff (8)",    "Bank", "Payroll Feb",     "640,000", "—"],
    ["06", "Diesel — 200L generator",          "Cash", "VND-Total-90",    " 92,000", "—"],
    ["07", "Stationery — Bulk",                "Bank", "FBN-TRF-462",     " 35,000", "—"],
    ["08", "Stripe processing fees",           "Card", "stripe_fee",      "  3,225", "—"],
    ["09", "Term-fee — JSS 3 — Tunde Salami",  "Card", "stripe_ch_3Bb...", "—", "120,000"],
    ["10", "Refund — over-payment",            "Bank", "REF-019",         " 12,000", "—"],
  ];

  doc.setFont("helvetica", "normal");
  doc.setTextColor(NAVY);
  rows.forEach((r, i) => {
    y += 8;
    if (i % 2 === 0) { doc.setFillColor("#F1F5F9"); doc.rect(14, y - 6, 182, 8, "F"); }
    doc.setFontSize(8);
    doc.text(r[0], 16, y);
    doc.text(r[1], 26, y);
    doc.text(r[2], 80, y);
    doc.text(r[3], 110, y);
    doc.text(r[4], 145, y);
    doc.text(r[5], 175, y);
  });

  // Totals
  y += 14;
  doc.setFillColor("#ECFDF5");
  doc.rect(14, y, 88, 30, "F");
  doc.setTextColor(GREEN);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("TOTAL INFLOW", 18, y + 8);
  doc.setFontSize(18);
  doc.text("₦ 513,000", 18, y + 22);

  doc.setFillColor("#FEF2F2");
  doc.rect(108, y, 88, 30, "F");
  doc.setTextColor("#B91C1C");
  doc.setFontSize(10);
  doc.text("TOTAL OUTFLOW", 112, y + 8);
  doc.setFontSize(18);
  doc.text("₦ 782,225", 112, y + 22);

  y += 36;
  doc.setFillColor("#EFF6FF");
  doc.rect(14, y, 182, 22, "F");
  doc.setTextColor(BLUE);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("NET POSITION (Feb 2026)", 18, y + 9);
  doc.setFontSize(16);
  doc.text("− ₦ 269,225  ·  Outstanding parent debt: ₦ 80,000 (10 debtors)", 18, y + 18);

  footer(doc);
  doc.save("CornerStreams_SampleFinancialStatement.pdf");
}
